import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../styles/globals.scss";
import Background from "@/components/background";
import Blur from "@/components/blur";
import Toaster from "@/components/toaster";

const poppins = Poppins({ weight: ["600", "500", "400", "300"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={poppins.className}>
        <Toaster />
        <Background />
        <Blur />
        {children}
      </body>
    </html>
  );
}
